# 服务配置
server:
  port: 8001

# 数据源配置
spring:
  application:
    name: JavaWebDemo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/positive_mysql?serverTimezone=UTC
    username: root
    password: root123
  redis:
    client-name: redis
    host: localhost
    port: 6379
    password: 123456
    timeout: 2000
    jedis:
      pool:
        max-wait: 1000


# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# 日志配置
logging:
  level:
    com.web.www.mapper.*: debug

